#targets:
#  $default:
#    builders:
#      source_gen|combining_builder:
#        generate_for:
#          include:
#            - lib/**.dart
#            - test/**.dart
#        options:
#          build_extensions:
#            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/gen/{{file}}.g.dart'
#            'test/{{path}}/{{file}}.dart': 'test/{{path}}/gen/{{file}}.g.dart'
#      freezed:freezed:
#        generate_for:
#          include:
#            - lib/**.dart
#            - test/**.dart
#        options:
#          build_extensions:
#            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/gen/{{file}}.freezed.dart'
#            'test/{{path}}/{{file}}.dart': 'test/{{path}}/gen/{{file}}.freezed.dart'
#          field_rename: none
#          explicit_to_json: true
#      json_serializable:
#        options:
#          field_rename: none
#          explicit_to_json: true
