arb-dir: lib/l10n/arb
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppStr
synthetic-package: false
nullable-getter: false
use-escaping: true