name: brain_box_ai
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.0.0

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  formz: 0.7.0
  equatable: ^2.0.5
  go_router: ^14.2.1
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.20.5
  google_fonts: 6.2.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  melos: 6.1.0
  freezed: 2.5.2
  freezed_annotation: 2.4.4
  retrofit: 4.1.0
  shimmer: ^2.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.1.0
  flutter_gen: ^5.6.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/on_boarding/
    - assets/auth/

flutter_gen:
  output: lib/assets/

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: false